In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('data.db')
table1 = "test_table"
table2 = "entry_cnt"
cmd = f'''
SELECT "{table1}".run_id,monitor_tag,workers,tasks_per_trial,trial,"{table1}".app_name,record_num FROM "{table1}"
JOIN "{table2}"
ON '{table1}'.run_id = '{table2}'.run_id
'''
tasks = pd.read_sql_query(cmd, conn)
tasks

,run_id,monitor_tag,workers,tasks_per_trial,trial,app_name,record_num
0,ee7bd3fa-2518-4b4f-b5fa-336d5f8c856b,htex,1,128,1,noop,2
1,8c86600c-6d64-4bed-b9de-aa5da43fb666,htex,1,128,1,sleep10ms,2
2,09ea21ed-e5be-4288-bbd1-05fec5e31710,htex,1,128,1,sleep100ms,3
3,0d3de61c-30e1-4ef9-a8dc-f00e3082a795,diaspora,1,128,1,noop,2
4,355ed8bd-7433-45d2-82ff-d5563cd406c2,diaspora,1,128,1,sleep10ms,2
...,...,...,...,...,...,...,...
139,9844a590-7fd0-4d54-9cab-4aa7f42f76eb,htex,128,128,3,sleep10ms,64
140,ab1b9e73-503c-481a-827b-de1676e8032c,htex,128,128,3,sleep100ms,64
141,95404a99-0424-481b-8d6e-53ce5481bf6b,diaspora,128,128,3,noop,59
142,bfd42705-3768-40f4-b58a-ef245f78001c,diaspora,128,128,3,sleep10ms,59
143,a296f766-55e7-4ad7-8dcb-6e8457cdb0d9,diaspora,128,128,3,sleep100ms,62